// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftMapper.Sample.Data;

#nullable disable

namespace ShiftMapper.Sample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820113031_AddBrandIsoCode")]
    partial class AddBrandIsoCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "United States",
                            FoundedYear = 1976,
                            ISOCode = "US",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Country = "South Korea",
                            FoundedYear = 1938,
                            ISOCode = "KR",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Japan",
                            FoundedYear = 1946,
                            ISOCode = "JP",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            Country = "United States",
                            FoundedYear = 1984,
                            ISOCode = "US",
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 5,
                            Country = "South Korea",
                            FoundedYear = 1958,
                            ISOCode = "KR",
                            Name = "LG"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Switzerland",
                            FoundedYear = 1981,
                            ISOCode = "CH",
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 7,
                            Country = "China",
                            FoundedYear = 2011,
                            ISOCode = "CN",
                            Name = "Anker"
                        },
                        new
                        {
                            Id = 8,
                            Country = "United States",
                            FoundedYear = 1964,
                            ISOCode = "US",
                            Name = "Bose"
                        });
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "ahmed.karim@example.com",
                            CustomerName = "Ahmed Karim",
                            IssuedAt = new DateTime(2026, 1, 12, 10, 30, 0, 0, DateTimeKind.Utc),
                            Number = "INV-2026-0001"
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "sara.hassan@example.com",
                            CustomerName = "Sara Hassan",
                            IssuedAt = new DateTime(2026, 2, 3, 14, 5, 0, 0, DateTimeKind.Utc),
                            Number = "INV-2026-0002"
                        },
                        new
                        {
                            Id = 3,
                            CustomerEmail = "omar.ali@example.com",
                            CustomerName = "Omar Ali",
                            IssuedAt = new DateTime(2026, 3, 20, 9, 45, 0, 0, DateTimeKind.Utc),
                            Number = "INV-2026-0003"
                        });
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InvoiceId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 999.00m
                        },
                        new
                        {
                            Id = 2,
                            InvoiceId = 1,
                            ProductId = 4,
                            Quantity = 2,
                            UnitPrice = 249.00m
                        },
                        new
                        {
                            Id = 3,
                            InvoiceId = 1,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 99.00m
                        },
                        new
                        {
                            Id = 4,
                            InvoiceId = 2,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 1199.00m
                        },
                        new
                        {
                            Id = 5,
                            InvoiceId = 2,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 229.00m
                        },
                        new
                        {
                            Id = 6,
                            InvoiceId = 3,
                            ProductId = 11,
                            Quantity = 2,
                            UnitPrice = 499.00m
                        },
                        new
                        {
                            Id = 7,
                            InvoiceId = 3,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 399.00m
                        },
                        new
                        {
                            Id = 8,
                            InvoiceId = 3,
                            ProductId = 26,
                            Quantity = 1,
                            UnitPrice = 429.00m
                        },
                        new
                        {
                            Id = 9,
                            InvoiceId = 3,
                            ProductId = 23,
                            Quantity = 3,
                            UnitPrice = 65.00m
                        });
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("StockId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "iPhone 15 Pro",
                            Price = 999.00m,
                            QuantityOnHand = 40,
                            Sku = "APL-IP15P",
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "MacBook Air M3",
                            Price = 1099.00m,
                            QuantityOnHand = 25,
                            Sku = "APL-MBA-M3",
                            StockId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "iPad Air 11\"",
                            Price = 599.00m,
                            QuantityOnHand = 30,
                            Sku = "APL-IPADAIR",
                            StockId = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Name = "AirPods Pro (2nd gen)",
                            Price = 249.00m,
                            QuantityOnHand = 120,
                            Sku = "APL-APP2",
                            StockId = 4
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Name = "Apple Watch Series 9",
                            Price = 399.00m,
                            QuantityOnHand = 55,
                            Sku = "APL-AWS9",
                            StockId = 2
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Name = "Galaxy S24 Ultra",
                            Price = 1199.00m,
                            QuantityOnHand = 35,
                            Sku = "SAM-S24U",
                            StockId = 1
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Name = "Galaxy Tab S9",
                            Price = 799.00m,
                            QuantityOnHand = 20,
                            Sku = "SAM-TABS9",
                            StockId = 2
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Name = "Galaxy Buds2 Pro",
                            Price = 229.00m,
                            QuantityOnHand = 90,
                            Sku = "SAM-BUDS2P",
                            StockId = 4
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            Name = "Odyssey G9 Monitor",
                            Price = 1299.00m,
                            QuantityOnHand = 12,
                            Sku = "SAM-ODYG9",
                            StockId = 3
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Name = "WH-1000XM5 Headphones",
                            Price = 399.00m,
                            QuantityOnHand = 60,
                            Sku = "SNY-WH1KXM5",
                            StockId = 4
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            Name = "PlayStation 5 Slim",
                            Price = 499.00m,
                            QuantityOnHand = 45,
                            Sku = "SNY-PS5S",
                            StockId = 1
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            Name = "Alpha a7 IV Camera",
                            Price = 2499.00m,
                            QuantityOnHand = 8,
                            Sku = "SNY-A7IV",
                            StockId = 3
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            Name = "Bravia XR A80L TV",
                            Price = 1799.00m,
                            QuantityOnHand = 10,
                            Sku = "SNY-XRA80L",
                            StockId = 2
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            Name = "XPS 15 Laptop",
                            Price = 1899.00m,
                            QuantityOnHand = 18,
                            Sku = "DEL-XPS15",
                            StockId = 1
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            Name = "UltraSharp U2723QE Monitor",
                            Price = 579.00m,
                            QuantityOnHand = 22,
                            Sku = "DEL-U2723QE",
                            StockId = 3
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            Name = "Latitude 7440",
                            Price = 1499.00m,
                            QuantityOnHand = 15,
                            Sku = "DEL-LAT7440",
                            StockId = 1
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 5,
                            Name = "OLED C4 55\" TV",
                            Price = 1499.00m,
                            QuantityOnHand = 14,
                            Sku = "LG-OLEDC4",
                            StockId = 2
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 5,
                            Name = "Gram 17 Laptop",
                            Price = 1699.00m,
                            QuantityOnHand = 10,
                            Sku = "LG-GRAM17",
                            StockId = 1
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 5,
                            Name = "UltraGear 27\" Monitor",
                            Price = 399.00m,
                            QuantityOnHand = 26,
                            Sku = "LG-UG27",
                            StockId = 3
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 6,
                            Name = "MX Master 3S Mouse",
                            Price = 99.00m,
                            QuantityOnHand = 150,
                            Sku = "LOG-MXM3S",
                            StockId = 4
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            Name = "MX Keys S Keyboard",
                            Price = 109.00m,
                            QuantityOnHand = 130,
                            Sku = "LOG-MXKEYSS",
                            StockId = 4
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            Name = "Brio 4K Webcam",
                            Price = 199.00m,
                            QuantityOnHand = 40,
                            Sku = "LOG-BRIO4K",
                            StockId = 2
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 7,
                            Name = "PowerCore 26800 Power Bank",
                            Price = 65.00m,
                            QuantityOnHand = 200,
                            Sku = "ANK-PC26800",
                            StockId = 4
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 7,
                            Name = "737 GaNPrime Charger",
                            Price = 109.00m,
                            QuantityOnHand = 110,
                            Sku = "ANK-737GAN",
                            StockId = 4
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 7,
                            Name = "Soundcore Liberty 4",
                            Price = 99.00m,
                            QuantityOnHand = 85,
                            Sku = "ANK-SCLIB4",
                            StockId = 2
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 8,
                            Name = "QuietComfort Ultra Headphones",
                            Price = 429.00m,
                            QuantityOnHand = 33,
                            Sku = "BOS-QCULTRA",
                            StockId = 2
                        });
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Erbil",
                            Code = "ERB-WH",
                            Name = "Central Warehouse"
                        },
                        new
                        {
                            Id = 2,
                            City = "Baghdad",
                            Code = "BGD-RS",
                            Name = "Baghdad Retail Store"
                        },
                        new
                        {
                            Id = 3,
                            City = "Sulaymaniyah",
                            Code = "SUL-DP",
                            Name = "Sulaymaniyah Depot"
                        },
                        new
                        {
                            Id = 4,
                            City = "Erbil",
                            Code = "ERB-OF",
                            Name = "Online Fulfillment"
                        });
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.InvoiceLine", b =>
                {
                    b.HasOne("ShiftMapper.Sample.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftMapper.Sample.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Product", b =>
                {
                    b.HasOne("ShiftMapper.Sample.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftMapper.Sample.Entities.Stock", "Stock")
                        .WithMany("Products")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ShiftMapper.Sample.Entities.Stock", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
